import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { gsap } from "gsap";

import {
  Activity, ArrowDown, ArrowRight, ArrowUpRight, Boxes, Check, ChevronRight, CircleDollarSign,
  Database, Github, LockKeyhole, Menu, Network, QrCode, ReceiptText, ScanLine, Search,
  ShieldCheck, Smartphone, Sparkles, WalletCards, Wifi, X, Zap,
} from "lucide-react";
import { VizhaBookScene } from "../components/VizhaBookScene";

export const Route = createFileRoute("/")({
  ssr: false,
  head: () => ({
    meta: [
      { title: "VizhaBook — Enterprise Digital Moi & Event Management Platform" },
      { name: "description", content: "VizhaBook is a cloud-based digital Moi and event management platform for weddings and traditional celebrations, featuring real-time multi-counter entries, QR guest check-in, UPI payments, digital receipts and live analytics." },
      { property: "og:title", content: "VizhaBook — Enterprise Digital Moi & Event Management Platform" },
      { property: "og:description", content: "Digitizing Tradition with Enterprise Engineering." },
      { property: "og:type", content: "website" },
      { property: "og:url", content: "/" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
    links: [{ rel: "canonical", href: "/" }],
    scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "SoftwareApplication", name: "VizhaBook", applicationCategory: "BusinessApplication", description: "Enterprise event and digital Moi management platform." }) }],
  }),
  component: VizhaBookHome,
});

const navItems = ["Overview", "Experience", "Workflow", "Features", "Technology", "Security"];
type ExplorerKey = "Dashboard" | "Functions" | "Moi Entry" | "Analytics" | "Security";
const workflowSteps = [
  { number: "01", title: "Create the celebration", eyebrow: "FUNCTION SETUP", description: "Start with the moments, people and places that make the event yours.", icon: Boxes },
  { number: "02", title: "Configure payments", eyebrow: "PAYMENT CONTROL", description: "Set the bank account, UPI handle and QR flow before the first guest arrives.", icon: WalletCards },
  { number: "03", title: "Capture every Moi", eyebrow: "MULTI-COUNTER ENTRY", description: "Reception, stage and management teams work from the same live ledger.", icon: CircleDollarSign },
  { number: "04", title: "Check in at the entrance", eyebrow: "GUEST EXPERIENCE", description: "A familiar QR journey turns arrival, payment and confirmation into one calm flow.", icon: ScanLine },
  { number: "05", title: "Verify before it is official", eyebrow: "HOST APPROVAL", description: "Approvals keep the official ledger trusted without slowing the room down.", icon: ShieldCheck },
  { number: "06", title: "Send a digital receipt", eyebrow: "BILINGUAL RECEIPT", description: "A thoughtful thank-you in English and Tamil, ready for the guest's record.", icon: ReceiptText },
  { number: "07", title: "See the celebration live", eyebrow: "LIVE ANALYTICS", description: "Collection, guests, gift types and event costs come into focus as the evening moves.", icon: Activity },
];

function VizhaBookHome() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeSection, setActiveSection] = useState("Overview");
  const [language, setLanguage] = useState<"EN" | "TA">("EN");
  const [workflowIndex, setWorkflowIndex] = useState(2);
  const [explorer, setExplorer] = useState<ExplorerKey>("Dashboard");

  useEffect(() => {
    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const reveals = gsap.utils.toArray<HTMLElement>(".scroll-reveal");
    reveals.forEach((element) => gsap.set(element, { y: reduceMotion ? 0 : 24, opacity: 0 }));
    const revealObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        gsap.to(entry.target, { y: 0, opacity: 1, duration: reduceMotion ? 0.01 : 0.85, ease: "power3.out", overwrite: true });
        revealObserver.unobserve(entry.target);
      });
    }, { rootMargin: "0px 0px -12%" });
    reveals.forEach((element) => revealObserver.observe(element));
    const observed = navItems.map((item) => document.getElementById(item.toLowerCase())).filter((element): element is HTMLElement => Boolean(element));
    const sectionObserver = new IntersectionObserver((entries) => {
      entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id));
    }, { rootMargin: "-35% 0px -55%" });
    observed.forEach((element) => sectionObserver.observe(element));
    return () => {
      revealObserver.disconnect();
      sectionObserver.disconnect();
      gsap.killTweensOf(reveals);
      reveals.forEach((element) => gsap.set(element, { clearProps: "transform,opacity" }));
    };
  }, []);

  const explorerContent = useMemo(() => ({
    Dashboard: { label: "Operations at a glance", title: "One room. Every signal.", metric: "₹8,42,500", sub: "collection in motion", bars: [32, 48, 42, 66, 61, 78, 96] },
    Functions: { label: "Your calendar, connected", title: "Every celebration has a clear beginning.", metric: "03", sub: "active functions", bars: [42, 42, 64, 50, 74, 55, 88] },
    "Moi Entry": { label: "Built for speed at the counter", title: "Capture a contribution in seconds.", metric: "+12", sub: "entries live", bars: [25, 42, 36, 68, 56, 80, 100] },
    Analytics: { label: "Turn celebration data into insight", title: "The evening, made legible.", metric: "1,284", sub: "guests checked in", bars: [22, 35, 53, 58, 72, 68, 90] },
    Security: { label: "Enterprise thinking", title: "Trust in every record.", metric: "JWT", sub: "authorization active", bars: [84, 72, 78, 89, 86, 95, 100] },
  } as const), []);

  return (
    <div className="min-h-screen overflow-x-hidden bg-ink text-text-primary">
      <div className="pointer-events-none fixed inset-0 z-0 overflow-hidden">
        <div className="aurora absolute -left-48 -top-48 h-[34rem] w-[34rem] rounded-full bg-success/10 blur-[110px]" />
        <div className="aurora-reverse absolute right-[-12rem] top-[20rem] h-[30rem] w-[30rem] rounded-full bg-brand/20 blur-[120px]" />
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,transparent_20%,var(--color-ink)_78%)]" />
        <div className="noise-field absolute inset-0 opacity-30" />
      </div>

      <header className="fixed inset-x-0 top-0 z-50 px-4 pt-4 sm:px-6 lg:px-8">
        <nav className="glass-panel mx-auto flex max-w-7xl items-center justify-between rounded-xl border border-line px-4 py-3 shadow-2xl shadow-ink/40 sm:px-5">
          <a href="#overview" className="group flex items-center gap-3" aria-label="VizhaBook home">
            <span className="grid size-9 place-items-center rounded-lg border border-accent/40 bg-brand text-accent transition-transform group-hover:rotate-6"><span className="font-tamil text-lg">வ</span></span>
            <span className="leading-none"><span className="block text-sm font-semibold tracking-tight">VizhaBook</span><span className="font-tamil text-[10px] text-text-faint">விழா புக்</span></span>
          </a>
          <div className="hidden items-center gap-6 text-xs text-text-secondary lg:flex">
            {navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className={`relative py-2 transition-colors hover:text-text-primary ${activeSection === item.toLowerCase() ? "text-text-primary" : ""}`}>{item}{activeSection === item.toLowerCase() && <span className="absolute inset-x-0 -bottom-1 mx-auto h-px w-5 bg-accent" />}</a>)}
          </div>
          <div className="flex items-center gap-2 sm:gap-3">
            <a href="https://github.com/manojrajm/VizhaBook" target="_blank" rel="noreferrer" className="hidden items-center gap-2 text-xs text-text-secondary transition-colors hover:text-text-primary sm:flex"><Github className="size-3.5" /> GitHub</a>
            <a href="https://vizhabooks.onrender.com" target="_blank" rel="noreferrer" className="hidden rounded-lg border border-accent/40 bg-accent/5 px-3 py-2 text-xs font-medium text-accent transition-colors hover:bg-accent/15 md:flex">Live Product <ArrowUpRight className="ml-1 inline size-3" /></a>
            <button type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close menu" : "Open menu"} className="grid size-9 place-items-center rounded-lg border border-line bg-surface text-text-primary lg:hidden">{menuOpen ? <X className="size-4" /> : <Menu className="size-4" />}</button>
          </div>
        </nav>
        <AnimatePresence>{menuOpen && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="glass-panel mx-auto mt-2 max-w-7xl rounded-xl border border-line p-4 lg:hidden"><div className="grid gap-1">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-3 text-sm text-text-secondary hover:bg-panel hover:text-text-primary">{item}</a>)}<a href="https://vizhabooks.onrender.com" target="_blank" rel="noreferrer" className="mt-2 rounded-lg bg-accent px-3 py-3 text-center text-sm font-semibold text-ink">Launch Live App</a></div></motion.div>}</AnimatePresence>
      </header>

      <main className="relative z-10">
        <section id="overview" className="relative min-h-[112vh] px-6 pb-20 pt-36 sm:px-10 lg:px-16 lg:pt-44">
          <VizhaBookScene />
          <div className="mx-auto grid max-w-7xl items-end gap-12 lg:grid-cols-[1.05fr_.95fr]">
            <div className="relative z-10 max-w-3xl">
              <div className="rise-in flex items-center gap-3 text-[10px] font-medium uppercase tracking-[0.32em] text-accent"><span className="h-px w-8 bg-accent" /> Enterprise Event Technology</div>
              <h1 className="mt-7 max-w-4xl text-balance text-[clamp(4rem,11vw,10rem)] font-extrabold leading-[.87] tracking-[-0.075em]">Tradition,<br /><span className="bg-gradient-to-r from-text-primary via-accent-soft to-success bg-clip-text text-transparent">Reimagined.</span></h1>
              <div className="mt-9 max-w-xl">
                <p className="text-2xl font-semibold tracking-tight sm:text-3xl">VizhaBook <span className="font-tamil text-accent">· விழா புக்</span></p>
                <p className="mt-4 text-sm leading-7 text-text-secondary sm:text-base">A modern digital Moi management platform built for weddings, receptions and traditional celebrations — combining real-time accounting, QR guest experiences, UPI payments and enterprise-grade engineering.</p>
                <div className="mt-7 flex flex-wrap items-center gap-3"><a href="#experience" className="group inline-flex items-center gap-2 rounded-lg bg-text-primary px-5 py-3 text-sm font-semibold text-ink transition-transform hover:-translate-y-0.5">Explore Experience <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></a><a href="https://vizhabooks.onrender.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-line bg-surface/70 px-5 py-3 text-sm font-medium text-text-primary transition-colors hover:border-accent/50">Launch Live App <ArrowUpRight className="size-4" /></a></div>
              </div>
            </div>
            <div className="relative z-10 hidden justify-self-end lg:block lg:max-w-xs"><div className="glass-panel rounded-2xl border border-line p-5"><div className="flex items-center justify-between text-[10px] uppercase tracking-[0.2em] text-text-faint"><span>From</span><span className="text-success">To</span></div><div className="mt-4 space-y-3"><div className="flex items-center justify-between rounded-lg border border-line bg-ink/50 px-3 py-3 text-sm text-text-faint"><span className="line-through">Handwritten records</span><span className="size-1.5 rounded-full bg-text-faint" /></div><div className="mx-auto h-5 w-px bg-gradient-to-b from-text-faint to-accent" /><div className="flex items-center justify-between rounded-lg border border-accent/30 bg-accent/5 px-3 py-3 text-sm"><span>Real-time intelligence</span><span className="signal-pulse size-1.5 rounded-full bg-accent" /></div></div><div className="mt-5 flex justify-between font-mono text-[9px] text-text-faint"><span>ENTRY_CREATED</span><span className="text-accent">DASHBOARD_SYNCED</span></div></div><div className="absolute -right-4 -top-3 rounded-full border border-accent/30 bg-brand px-3 py-1 font-mono text-[10px] text-accent">+12 live</div></div>
          </div>
          <div className="absolute bottom-8 left-6 flex items-center gap-3 text-[10px] uppercase tracking-[0.24em] text-text-faint sm:left-10 lg:left-16"><ArrowDown className="size-4 animate-bounce text-accent" /> Scroll to enter the ledger</div>
        </section>

        <section id="experience" className="scroll-reveal border-y border-line bg-surface/60 px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-4"><p className="text-[10px] uppercase tracking-[0.3em] text-accent">The Platform</p><h2 className="mt-5 text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">Your celebration.<br />One intelligent<br /><span className="text-text-secondary">system.</span></h2><p className="mt-6 max-w-sm text-sm leading-7 text-text-secondary">Every contribution, receipt and expense — one live ledger your whole team can see, sync and approve in real time.</p><div className="mt-8 space-y-3 text-sm text-text-secondary"><p className="flex items-center gap-3"><Wifi className="size-4 text-success" /> Real-time multi-counter entries</p><p className="flex items-center gap-3"><QrCode className="size-4 text-accent" /> Digital UPI collections & QR check-in</p><p className="flex items-center gap-3"><ReceiptText className="size-4 text-brand" /> Host approvals & bilingual receipts</p></div></div><Dashboard className="lg:col-span-8" /></div></section>

         <section id="workflow" className="scroll-reveal px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.3em] text-accent">The complete event journey</p><h2 className="mt-5 max-w-2xl text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">One celebration.<br /><span className="text-text-secondary">One connected workflow.</span></h2></div><p className="max-w-xs text-sm leading-6 text-text-secondary">From the first function detail to the final dashboard sync, the system moves at the speed of the room.</p></div><div className="mt-16 grid gap-10 lg:grid-cols-[.3fr_.7fr] lg:gap-16"><div className="space-y-2">{workflowSteps.map((step, index) => { const Icon = step.icon; return <button key={step.number} type="button" onClick={() => setWorkflowIndex(index)} className={`group flex w-full items-center gap-4 border-l px-4 py-3 text-left transition-colors ${workflowIndex === index ? "border-accent bg-panel/60" : "border-line hover:border-text-faint"}`}><span className={`font-mono text-xs ${workflowIndex === index ? "text-accent" : "text-text-faint"}`}>{step.number}</span><span className={`flex-1 text-sm ${workflowIndex === index ? "text-text-primary" : "text-text-secondary"}`}>{step.title}</span><Icon className={`size-4 ${workflowIndex === index ? "text-accent" : "text-text-faint"}`} /></button>; })}</div><WorkflowVisual step={workflowSteps[workflowIndex] ?? workflowSteps[0]} /></div></div></section>

        <section id="features" className="scroll-reveal border-y border-line bg-surface/50 px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Product intelligence</p><h2 className="mt-5 text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">Designed for the moment that matters.</h2></div><div className="mt-16 grid gap-px overflow-hidden border border-line bg-line md:grid-cols-2"><FeaturePanel icon={CircleDollarSign} eyebrow="Moi Entry" title="Built for speed at the counter." copy="Reception / stage source, guest details, cash, UPI, jewel and gift item — captured without losing the rhythm of the line." type="entry" /><FeaturePanel icon={Search} eyebrow="Digital Ledger" title="Every contribution. Searchable forever." copy="Filter by guest, village, city, source, payment mode or function, then export a clear record." type="ledger" /><FeaturePanel icon={Activity} eyebrow="Analytics" title="Turn celebration data into insight." copy="Collection trend, relationship distribution, gift types and hourly peaks, drawn live as the event unfolds." type="analytics" /><FeaturePanel icon={WalletCards} eyebrow="Expense Management" title="Collections and costs. In one place." copy="Keep catering, venue, decoration and vendor expenses close to the same event balance." type="expense" /></div></div></section>

        <section className="relative overflow-hidden px-6 py-36 sm:px-10 lg:px-16 lg:py-52"><div className="grid-lines pointer-events-none absolute inset-0 opacity-20" /><div className="relative mx-auto max-w-5xl text-center"><Sparkles className="mx-auto mb-10 size-5 text-accent" /><p className="font-tamil text-2xl leading-[1.9] text-text-primary sm:text-4xl">பாரம்பரியம் மாற வேண்டியதில்லை.<br />அதை நிர்வகிக்கும் தொழில்நுட்பம் மட்டும் மாறலாம்.</p><p className="mx-auto mt-10 max-w-lg text-lg leading-8 text-text-secondary">Tradition doesn't need to change.<br />The technology supporting it can.</p></div></section>

         <section id="technology" className="scroll-reveal border-y border-line bg-surface/60 px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Realtime engine</p><h2 className="mt-5 max-w-3xl text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">Built for the busiest<br /><span className="text-text-secondary">moment of the celebration.</span></h2></div><span className="inline-flex items-center gap-2 rounded-full border border-success/30 bg-success/5 px-3 py-2 font-mono text-[10px] text-success"><span className="signal-pulse size-1.5 rounded-full bg-success" /> Socket.io WebSockets</span></div><NetworkVisual /><DeviceFleetVisual /><div className="mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><EngineeringStat eyebrow="REAL-TIME" title="Multi-device synchronization" icon={Wifi} /><EngineeringStat eyebrow="CLOUD" title="PostgreSQL-backed architecture" icon={Database} /><EngineeringStat eyebrow="PWA" title="Desktop → tablet → mobile" icon={Smartphone} /><EngineeringStat eyebrow="BILINGUAL" title="English + தமிழ்" icon={Sparkles} /></div></div></section>

        <section id="security" className="scroll-reveal px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.42fr_.58fr] lg:items-center"><div><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Enterprise posture</p><h2 className="mt-5 text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">Trust in<br /><span className="text-text-secondary">every record.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-text-secondary">Security is not a badge on the page. It is a series of deliberate boundaries around each event, entry and approval.</p><div className="mt-9 space-y-3 text-sm text-text-secondary"><p className="flex items-center gap-3"><LockKeyhole className="size-4 text-accent" /> JWT authorization</p><p className="flex items-center gap-3"><Database className="size-4 text-accent" /> PostgreSQL with tenant-aware records</p><p className="flex items-center gap-3"><ShieldCheck className="size-4 text-accent" /> Atomic transaction handling</p></div></div><SecurityArchitecture /></div></section>

         <section className="scroll-reveal border-y border-line bg-brand-deep/40 px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-10 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Product explorer</p><h2 className="mt-5 text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">See the system<br /><span className="text-text-secondary">from every angle.</span></h2></div><div className="flex max-w-xl flex-wrap gap-2">{Object.keys(explorerContent).map((item) => <button key={item} type="button" onClick={() => setExplorer(item as ExplorerKey)} className={`rounded-lg border px-3 py-2 text-xs transition-colors ${explorer === item ? "border-accent/50 bg-accent/10 text-accent" : "border-line bg-surface text-text-secondary hover:border-text-faint"}`}>{item}</button>)}</div></div><ExplorerPreview data={explorerContent[explorer]} /></div></section>

        <section className="scroll-reveal px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-5"><div><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Event day, in focus</p><h2 className="mt-5 text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-6xl">6:42 PM.<br /><span className="text-text-secondary">The hall is full.</span></h2></div><div className="hidden font-mono text-xs text-success sm:block">LIVE / 18:21:12</div></div><div className="mt-16 grid gap-px border border-line bg-line md:grid-cols-5">{["6:42:01", "6:42:03", "6:42:07", "6:42:10", "6:42:11"].map((time, index) => <div key={time} className="bg-surface p-5"><span className="font-mono text-[10px] text-accent">{time}</span><div className="mt-12 size-2 rounded-full bg-success" /><p className="mt-5 text-sm leading-6 text-text-primary">{["Guest arrives.", "QR scanned.", "UPI payment submitted.", "Host approval.", "Connected screens synchronized."][index]}</p><p className="mt-3 font-mono text-[9px] text-text-faint">{["ENTRY_CREATED", "CHECK_IN_STARTED", "PAYMENT_SUBMITTED", "ENTRY_APPROVED", "DASHBOARD_SYNCED"][index]}</p></div>)}</div><p className="mt-16 max-w-4xl text-4xl font-bold leading-[.98] tracking-[-0.05em] sm:text-7xl">VizhaBook keeps<br /><span className="text-accent">everything moving.</span></p></div></section>

        <section className="scroll-reveal border-y border-line bg-surface/60 px-6 py-28 sm:px-10 lg:px-16 lg:py-40"><div className="mx-auto max-w-7xl"><div className="grid overflow-hidden border border-line lg:grid-cols-2"><div className="relative min-h-[26rem] bg-elevated p-8 sm:p-12"><div className="absolute inset-0 grid-lines opacity-15" /><div className="relative"><p className="text-[10px] uppercase tracking-[0.3em] text-text-faint">Before</p><h2 className="mt-6 text-4xl font-bold tracking-[-0.05em] text-text-secondary">Traditional<br />Moi Book</h2><ul className="mt-10 space-y-4 text-sm text-text-faint"><li>Paper ledger</li><li>Manual calculations</li><li>Single-location access</li><li>Difficult searching</li><li>No live analytics</li></ul></div></div><div className="relative min-h-[26rem] bg-brand-deep p-8 sm:p-12"><div className="relative"><p className="text-[10px] uppercase tracking-[0.3em] text-accent">After</p><h2 className="mt-6 text-4xl font-bold tracking-[-0.05em]">VizhaBook</h2><ul className="mt-10 space-y-4 text-sm text-text-secondary"><li className="flex items-center gap-2"><Check className="size-4 text-accent" /> Cloud ledger</li><li className="flex items-center gap-2"><Check className="size-4 text-accent" /> Real-time calculations</li><li className="flex items-center gap-2"><Check className="size-4 text-accent" /> Multi-device access</li><li className="flex items-center gap-2"><Check className="size-4 text-accent" /> Instant search</li><li className="flex items-center gap-2"><Check className="size-4 text-accent" /> Live analytics</li></ul></div></div></div></div></section>

        <section className="relative overflow-hidden px-6 py-32 sm:px-10 lg:px-16 lg:py-44"><div className="absolute left-1/2 top-1/2 size-[30rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-accent/10" /><div className="absolute left-1/2 top-1/2 size-[21rem] -translate-x-1/2 -translate-y-1/2 rounded-full border border-accent/10" /><div className="relative mx-auto max-w-5xl text-center"><p className="text-[10px] uppercase tracking-[0.3em] text-accent">Don't just read about VizhaBook.</p><h2 className="mt-6 text-5xl font-bold leading-[.9] tracking-[-0.07em] sm:text-8xl">Experience it.</h2><p className="mx-auto mt-8 max-w-lg text-sm leading-7 text-text-secondary">The live product is ready for the moments that matter.</p><div className="mt-9 flex flex-wrap justify-center gap-3"><a href="https://vizhabooks.onrender.com" target="_blank" rel="noreferrer" className="group inline-flex items-center gap-2 rounded-lg bg-text-primary px-6 py-3.5 text-sm font-semibold text-ink transition-transform hover:-translate-y-0.5">Launch VizhaBook <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-1" /></a><a href="https://github.com/manojrajm/VizhaBook" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-line bg-surface px-6 py-3.5 text-sm font-medium text-text-primary hover:border-accent/50"><Github className="size-4" /> View GitHub</a></div><div className="mt-10 flex flex-wrap justify-center gap-5 font-mono text-[10px] text-text-faint"><span>LIVE / vizhabooks.onrender.com</span><span>API / vizhabooks-backend.onrender.com</span></div></div></section>
      </main>

      <footer className="relative z-10 border-t border-line px-6 py-12 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-4"><div className="md:col-span-2"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg border border-accent/40 bg-brand text-accent"><span className="font-tamil">வ</span></span><span><span className="block text-sm font-semibold">VizhaBook</span><span className="font-tamil text-[10px] text-text-faint">விழா புக்</span></span></div><p className="mt-4 max-w-sm text-xs leading-6 text-text-faint">Enterprise Event & Digital Moi Management Platform.<br />Digitizing Tradition with Enterprise Engineering.</p></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-text-faint">Product</p><div className="mt-4 grid gap-2 text-sm text-text-secondary">{navItems.slice(0, 4).map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="hover:text-text-primary">{item}</a>)}</div></div><div><p className="text-[10px] uppercase tracking-[0.2em] text-text-faint">Resources</p><div className="mt-4 grid gap-2 text-sm text-text-secondary"><a href="https://vizhabooks.onrender.com" target="_blank" rel="noreferrer" className="hover:text-text-primary">Live Product</a><a href="https://vizhabooks-backend.onrender.com" target="_blank" rel="noreferrer" className="hover:text-text-primary">Backend API</a><a href="https://github.com/manojrajm" target="_blank" rel="noreferrer" className="hover:text-text-primary">Engineered by ManojRaj</a></div></div></div><div className="mx-auto mt-12 flex max-w-7xl flex-col justify-between gap-3 border-t border-line pt-6 text-[10px] text-text-faint sm:flex-row"><span>© 2026 VizhaBook. MIT License.</span><span>Built for celebrations. Engineered for scale.</span></div></footer>
    </div>
  );
}

function Dashboard({ className = "" }: { className?: string }) { return <div className={`glass-panel rounded-2xl border border-line p-3 shadow-2xl shadow-ink/50 ${className}`}><div className="flex items-center justify-between border-b border-line px-3 pb-3"><div className="flex gap-1.5"><span className="size-2.5 rounded-full bg-brand" /><span className="size-2.5 rounded-full bg-accent/70" /><span className="size-2.5 rounded-full bg-success/70" /></div><span className="font-mono text-[10px] text-text-faint">vizhabook.app / dashboard</span></div><div className="mt-3 grid gap-3 sm:grid-cols-4"><Metric label="Total Collection" value="₹8,42,500" accent /><Metric label="Guests" value="1,284" /><Metric label="Cash" value="₹5.9L" /><Metric label="Digital" value="₹2.52L" /></div><div className="mt-3 grid gap-3 lg:grid-cols-5"><div className="rounded-xl border border-line bg-ink/50 p-4 lg:col-span-3"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-text-faint">Live Collection Trend</span><span className="font-mono text-[9px] text-success">● live</span></div><div className="mt-5 flex h-28 items-end gap-2">{[35, 48, 42, 64, 58, 76, 70, 96].map((height, index) => <span key={index} className={`flex-1 rounded-t-sm ${index > 5 ? "bg-accent" : index > 3 ? "bg-brand" : "bg-success/50"}`} style={{ height: `${height}%`, opacity: .35 + index * .08 }} />)}</div></div><div className="rounded-xl border border-line bg-ink/50 p-4 lg:col-span-2"><div className="flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-text-faint">Recent Moi Entries</span><span className="font-tamil text-[10px] text-accent">மொய்</span></div><div className="mt-3 divide-y divide-line">{[["Arun Kumar", "₹1,001", "Madurai"], ["Senthil Raj", "₹2,001", "Rajapalayam"], ["Meena", "₹5,001", "Chennai"]].map(([name, amount, place]) => <div key={name} className="flex items-center justify-between py-2.5 text-xs"><div><p>{name}</p><p className="mt-0.5 text-[10px] text-text-faint">{place}</p></div><span className="font-mono text-accent">{amount}</span></div>)}</div></div></div></div>; }

function Metric({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="rounded-xl border border-line bg-ink/50 p-4"><p className="text-[10px] uppercase tracking-wider text-text-faint">{label}</p><p className={`mt-2 text-2xl font-bold tracking-tight ${accent ? "text-accent" : "text-text-primary"}`}>{value}</p></div>; }

function WorkflowVisual({ step }: { step: (typeof workflowSteps)[number] | undefined }) {
  if (!step) return null;
  const Icon = step.icon;
  return <div className="glass-panel min-h-[27rem] rounded-2xl border border-line p-6 sm:p-10"><div className="flex items-start justify-between"><div><span className="font-mono text-[10px] uppercase tracking-[0.25em] text-accent">{step.eyebrow}</span><h3 className="mt-4 max-w-xl text-3xl font-bold tracking-[-0.04em] sm:text-5xl">{step.title}</h3><p className="mt-4 max-w-lg text-sm leading-7 text-text-secondary">{step.description}</p></div><span className="grid size-12 place-items-center rounded-xl border border-accent/30 bg-accent/5 text-accent"><Icon className="size-5" /></span></div><div className="mt-12 grid gap-3 sm:grid-cols-3">{step.number === "03" ? ["Reception Counter", "Stage Present", "Manager Dashboard"].map((label, i) => <div key={label} className="relative rounded-xl border border-line bg-ink/60 p-4"><div className="flex items-center justify-between text-[10px] text-text-faint"><span>0{i + 1}</span><Wifi className="size-3 text-success" /></div><p className="mt-10 text-sm">{label}</p><p className="mt-2 font-mono text-[10px] text-accent">{i === 0 ? "Arun Kumar · ₹1,001" : i === 1 ? "Senthil Raj · ₹2,001" : "+12 entries live"}</p>{i < 2 && <span className="absolute -right-2 top-1/2 hidden size-4 translate-y-[-50%] rounded-full border border-accent bg-brand sm:block" />}</div>) : <div className="sm:col-span-3 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-line bg-ink/60 p-5"><p className="text-[10px] uppercase tracking-wider text-text-faint">{step.number === "02" ? "Default UPI" : step.number === "04" ? "Entrance QR" : step.number === "05" ? "Approval queue" : step.number === "06" ? "Receipt preview" : "Function name"}</p><p className="mt-3 text-xl font-semibold">{step.number === "02" ? "manoj@upi" : step.number === "04" ? "SCAN TO CHECK IN" : step.number === "05" ? "Karthik S · ₹2,501" : step.number === "06" ? "உங்கள் அன்பான மொய்..." : "Manoj & Preeti Wedding"}</p><div className="mt-8 h-1 overflow-hidden rounded-full bg-line"><div className="h-full w-3/4 bg-accent" /></div></div><div className="rounded-xl border border-line bg-brand-deep/70 p-5"><p className="text-[10px] uppercase tracking-wider text-text-faint">Next signal</p><p className="mt-3 text-xl font-semibold text-accent">{step.number === "07" ? "DASHBOARD_SYNCED" : "READY_FOR_THE_ROOM"}</p><p className="mt-3 font-mono text-[10px] text-success">● system online</p></div></div>}</div></div>;
}

function FeaturePanel({ icon: Icon, eyebrow, title, copy, type }: { icon: typeof Activity; eyebrow: string; title: string; copy: string; type: string }) { return <article className="bg-surface p-7 sm:p-10"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-lg border border-accent/30 bg-accent/5 text-accent"><Icon className="size-4" /></span><span className="font-mono text-[9px] text-text-faint">0{type === "entry" ? 1 : type === "ledger" ? 2 : type === "analytics" ? 3 : 4}</span></div><p className="mt-16 text-[10px] uppercase tracking-[0.25em] text-accent">{eyebrow}</p><h3 className="mt-4 max-w-md text-3xl font-bold leading-[.98] tracking-[-0.04em] sm:text-4xl">{title}</h3><p className="mt-5 max-w-md text-sm leading-7 text-text-secondary">{copy}</p><div className="mt-10 rounded-xl border border-line bg-ink p-4">{type === "entry" && <div className="space-y-2">{["Guest details", "₹1,001 · Cash", "Source · Reception"].map((line) => <div key={line} className="flex items-center justify-between border-b border-line py-2 text-xs"><span className="text-text-secondary">{line}</span><Check className="size-3 text-success" /></div>)}</div>}{type === "ledger" && <div><div className="flex items-center gap-2 rounded-lg border border-line bg-surface px-3 py-2 text-xs text-text-faint"><Search className="size-3" /> Search the ledger...</div><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-full bg-brand px-2 py-1 text-[9px] text-accent">All sources</span><span className="rounded-full border border-line px-2 py-1 text-[9px] text-text-faint">Cash</span><span className="rounded-full border border-line px-2 py-1 text-[9px] text-text-faint">UPI</span></div></div>}{type === "analytics" && <div className="flex h-20 items-end gap-1.5">{[30, 46, 40, 58, 52, 70, 64, 88].map((height, i) => <span key={i} className={`flex-1 rounded-t-sm ${i > 5 ? "bg-accent" : "bg-brand"}`} style={{ height: `${height}%`, opacity: .45 + i * .06 }} />)}</div>}{type === "expense" && <div className="grid grid-cols-3 gap-2 text-center">{[["Collection", "₹8.42L"], ["Expense", "₹1.28L"], ["Balance", "₹7.14L"]].map(([label, value]) => <div key={label} className="rounded-lg border border-line p-2"><p className="text-[9px] text-text-faint">{label}</p><p className="mt-2 text-sm text-accent">{value}</p></div>)}</div>}</div></article>; }

function NetworkVisual() { const nodes = ["VIZHABOOK CLOUD", "Reception 01", "Reception 02", "Stage Counter", "Entrance QR", "Guest Phone", "Host Dashboard"]; return <div className="relative mt-16 min-h-[24rem] overflow-hidden rounded-2xl border border-line bg-ink p-6 sm:p-10"><div className="absolute inset-0 grid-lines opacity-20" /><div className="relative grid min-h-[20rem] place-items-center"><div className="grid size-36 place-items-center rounded-full border border-accent/50 bg-brand/60 text-center shadow-[0_0_70px_var(--color-brand)]"><Network className="mx-auto size-6 text-accent" /><span className="mt-2 block font-mono text-[9px] text-accent">VIZHABOOK<br />CLOUD</span></div>{nodes.slice(1).map((node, index) => { const positions = ["left-2 top-8", "left-1/4 bottom-3", "right-1/4 bottom-3", "right-2 top-8", "left-4 top-1/2", "right-4 top-1/2"]; return <div key={node} className={`absolute ${positions[index]} flex items-center gap-2 rounded-lg border border-line bg-surface px-3 py-2 font-mono text-[9px] text-text-secondary`}><span className="signal-pulse size-1.5 rounded-full bg-success" />{node}</div>; })}<svg className="pointer-events-none absolute inset-0 h-full w-full" viewBox="0 0 800 320" preserveAspectRatio="none" aria-hidden="true"><path d="M400 160 L120 55 M400 160 L260 280 M400 160 L540 280 M400 160 L680 55 M400 160 L95 160 M400 160 L705 160" fill="none" stroke="var(--color-accent)" strokeDasharray="4 9" strokeOpacity=".35" /></svg></div><div className="absolute bottom-5 left-6 right-6 flex flex-wrap justify-between gap-3 font-mono text-[9px] text-text-faint sm:left-10 sm:right-10"><span>ENTRY_CREATED</span><span>PAYMENT_SUBMITTED</span><span className="text-accent">ENTRY_APPROVED</span><span>DASHBOARD_SYNCED</span></div></div>; }

function EngineeringStat({ eyebrow, title, icon: Icon }: { eyebrow: string; title: string; icon: typeof Wifi }) { return <div className="border-l border-line py-2 pl-4"><Icon className="size-4 text-accent" /><p className="mt-6 font-mono text-[9px] tracking-[0.2em] text-text-faint">{eyebrow}</p><p className="mt-2 text-sm font-semibold leading-6 text-text-secondary">{title}</p></div>; }

function SecurityArchitecture() { return <div className="glass-panel rounded-2xl border border-line p-6 sm:p-10"><div className="flex items-center justify-between border-b border-line pb-5"><span className="font-mono text-[10px] text-text-faint">ARCHITECTURE / TRUST BOUNDARY</span><ShieldCheck className="size-5 text-accent" /></div><div className="mt-8 space-y-3">{[["React Client", "user surfaces"], ["REST API / WebSockets", "controlled transport"], ["JWT Authorization", "verified access"], ["PostgreSQL", "durable records"]].map(([title, sub], index) => <div key={title}><div className={`flex items-center justify-between rounded-lg border px-4 py-4 ${index === 2 ? "border-accent/40 bg-accent/5" : "border-line bg-ink/50"}`}><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-[10px] text-text-faint">{sub}</p></div><Check className="size-4 text-success" /></div>{index < 3 && <div className="mx-auto h-4 w-px bg-accent/40" />}</div>)}</div></div>; }

function ExplorerPreview({ data }: { data: { label: string; title: string; metric: string; sub: string; bars: readonly number[] } }) { return <motion.div key={data.title} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }} className="mt-14 grid gap-10 lg:grid-cols-[.4fr_.6fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[0.25em] text-accent">{data.label}</p><h3 className="mt-5 max-w-md text-3xl font-bold leading-[.98] tracking-[-0.04em] sm:text-5xl">{data.title}</h3><div className="mt-9 flex items-end gap-4"><span className="text-5xl font-bold tracking-[-0.06em] text-accent">{data.metric}</span><span className="mb-1 max-w-[8rem] text-xs leading-5 text-text-faint">{data.sub}</span></div></div><div className="rounded-2xl border border-line bg-ink p-5 sm:p-7"><div className="flex items-center justify-between border-b border-line pb-4"><span className="font-mono text-[10px] text-text-faint">LIVE PRODUCT SURFACE</span><span className="font-mono text-[10px] text-success">● ACTIVE</span></div><div className="mt-8 flex h-48 items-end gap-2">{data.bars.map((height, i) => <span key={i} className={`flex-1 rounded-t-sm ${i > 5 ? "bg-accent" : i > 3 ? "bg-brand" : "bg-success/50"}`} style={{ height: `${height}%`, opacity: .4 + i * .07 }} />)}</div><div className="mt-4 flex justify-between font-mono text-[9px] text-text-faint"><span>18:00</span><span>19:00</span><span>20:00</span><span>21:00</span></div></div></motion.div>; }

function DeviceFleetVisual() {
  const fleetRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const fleet = fleetRef.current;
    if (!fleet) return;
    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const context = gsap.context(() => {
      const shells = gsap.utils.toArray<HTMLElement>(".device-shell", fleet);
      gsap.set(shells, { y: reduceMotion ? 0 : 24, opacity: 0, rotateX: reduceMotion ? 0 : 8 });
      const observer = new IntersectionObserver((entries) => {
        if (!entries.some((entry) => entry.isIntersecting)) return;
        gsap.to(shells, { y: 0, opacity: 1, rotateX: 0, duration: reduceMotion ? 0.01 : 1, stagger: reduceMotion ? 0 : 0.12, ease: "power3.out" });
        observer.disconnect();
      }, { rootMargin: "0px 0px -18%" });
      observer.observe(fleet);
      if (!reduceMotion) {
        gsap.to(".device-signal", { y: -5, opacity: 0.72, duration: 1.8, stagger: 0.22, repeat: -1, yoyo: true, ease: "sine.inOut" });
        gsap.to(".device-sync", { strokeDashoffset: -32, duration: 2.6, repeat: -1, ease: "none" });
      }
      return () => observer.disconnect();
    }, fleet);
    return () => context.revert();
  }, []);

  return <div ref={fleetRef} className="relative mt-12 overflow-hidden rounded-2xl border border-line bg-ink px-5 py-8 sm:px-10 sm:py-10">
    <div className="absolute inset-0 grid-lines opacity-20" />
    <div className="relative flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between">
      <div className="max-w-sm">
        <p className="font-mono text-[10px] uppercase tracking-[0.25em] text-accent">One live surface</p>
        <h3 className="mt-4 text-3xl font-bold leading-[.98] tracking-[-0.04em] sm:text-4xl">From desk to device, the room stays in sync.</h3>
        <p className="mt-4 text-sm leading-7 text-text-secondary">Counter entries move through the same trusted flow — whether the team is on desktop, tablet or mobile.</p>
      </div>
      <div className="relative min-h-[15rem] flex-1 lg:max-w-2xl">
        <svg className="pointer-events-none absolute inset-x-8 top-1/2 h-20 w-[calc(100%-4rem)] -translate-y-1/2" viewBox="0 0 520 80" preserveAspectRatio="none" aria-hidden="true">
          <path className="device-sync" d="M18 40 C120 8 160 72 260 40 S400 8 502 40" fill="none" stroke="var(--color-accent)" strokeDasharray="3 13" strokeOpacity=".65" />
        </svg>
        <div className="relative flex items-end justify-center gap-3 sm:gap-7">
          <div className="device-shell w-24 origin-bottom [transform-style:preserve-3d] sm:w-32"><div className="relative aspect-[9/16] rounded-[1.15rem] border-2 border-text-faint/50 bg-elevated p-1.5 shadow-2xl shadow-ink/70"><div className="h-full overflow-hidden rounded-[.8rem] border border-line bg-surface p-2"><div className="flex items-center justify-between"><span className="size-1.5 rounded-full bg-success" /><span className="font-mono text-[6px] text-text-faint">09:41</span></div><div className="mt-4 h-1.5 w-2/3 rounded-full bg-accent/80" /><div className="mt-2 h-1 w-full rounded-full bg-line" /><div className="mt-7 space-y-1.5"><span className="device-signal block h-4 rounded-sm bg-brand/80" /><span className="device-signal block h-4 rounded-sm bg-success/40" /><span className="device-signal block h-4 rounded-sm bg-accent/50" /></div><p className="mt-3 font-mono text-[6px] text-accent">COUNTER 01</p></div></div><p className="mt-3 text-center font-mono text-[8px] text-text-faint">MOBILE</p></div>
          <div className="device-shell w-32 origin-bottom [transform-style:preserve-3d] sm:w-44"><div className="relative aspect-[4/3] rounded-[1rem] border-2 border-accent/40 bg-elevated p-1.5 shadow-2xl shadow-brand/30"><div className="h-full overflow-hidden rounded-[.7rem] border border-line bg-surface p-3"><div className="flex items-center justify-between border-b border-line pb-2"><span className="font-mono text-[7px] text-text-faint">VIZHABOOK / LIVE</span><span className="size-1.5 rounded-full bg-success" /></div><div className="mt-3 flex items-end gap-1.5"><span className="h-8 flex-1 rounded-t-sm bg-success/60" /><span className="h-12 flex-1 rounded-t-sm bg-brand" /><span className="h-16 flex-1 rounded-t-sm bg-accent" /><span className="h-20 flex-1 rounded-t-sm bg-accent-soft" /></div><div className="mt-3 flex gap-2"><span className="h-1.5 flex-1 rounded-full bg-line" /><span className="h-1.5 w-1/3 rounded-full bg-success/60" /></div></div></div><p className="mt-3 text-center font-mono text-[8px] text-accent">DESKTOP</p></div>
          <div className="device-shell w-24 origin-bottom [transform-style:preserve-3d] sm:w-32"><div className="relative aspect-[3/4] rounded-[1rem] border-2 border-success/40 bg-elevated p-1.5 shadow-2xl shadow-success/10"><div className="h-full overflow-hidden rounded-[.75rem] border border-line bg-surface p-2"><div className="mx-auto h-1 w-7 rounded-full bg-line" /><div className="mt-4 rounded-md border border-line bg-ink p-2"><span className="font-mono text-[6px] text-text-faint">LIVE RECEIPT</span><p className="mt-2 font-tamil text-[8px] text-accent">மொய் பதிவு</p><p className="mt-2 font-mono text-[7px] text-text-secondary">₹2,501 · VERIFIED</p></div><div className="mt-3 h-1.5 w-full rounded-full bg-success/60" /></div></div><p className="mt-3 text-center font-mono text-[8px] text-text-faint">TABLET</p></div>
        </div>
      </div>
    </div>
  </div>;
}